vim.keymap.set("i", "<C-c>", "<Esc>")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("v", "//", 'y/<C-R>"<CR>')

vim.keymap.set('i', '<A-a>', 'á', {noremap = true, silent = true})
vim.keymap.set('i', '<A-e>', 'é', {noremap = true, silent = true})
vim.keymap.set('i', '<A-i>', 'í', {noremap = true, silent = true})
vim.keymap.set('i', '<A-o>', 'ó', {noremap = true, silent = true})
vim.keymap.set('i', '<A-u>', 'ú', {noremap = true, silent = true})
vim.keymap.set('i', '<A-n>', 'ñ', {noremap = true, silent = true})
