local configs = {
  --  "bqf",
  "nvim-gps",
  "colorizer",
  "comment",
  "copilot",
  "debugger",
  "diffview",
  "fugitive",
  "feline",
  "gitsigns",
  "harpoon",
  "indent-blankline",
  "lsp-config",
  -- "lualine",
  "neoscroll",
  "nvim_autopairs",
  "nvimtree",
  "snippy",
  "spectre",
  "telescope",
  "todo_comments",
  "toggleterm",
  "treesitter",
  "trouble",
  "vim-test",
  "zen-mode",
  -- "floaterm",
  -- "hop",
  -- "tabline",
}

for _, plugin in ipairs(configs) do
  require("acc_plugs." .. plugin)
end
