vim.cmd("hi clear")
vim.cmd("colo accent")
vim.cmd("hi Normal guibg=#101010")

vim.cmd("hi @variable guifg=#e0e0e0")
vim.cmd("hi @parameter guifg=#e0e0e0")

vim.cmd("hi @constant guifg=#e06060")
vim.cmd("hi @number guifg=#e06060")
vim.cmd("hi @function guifg=#e06060")
vim.cmd("hi @string guifg=#e06060")
vim.cmd("hi @macro guifg=#e06060")

vim.cmd("hi @type guifg=#e5c07b")
vim.cmd("hi @conditional guifg=#e5c07b")
vim.cmd("hi @keyword guifg=#e5c07b")
vim.cmd("hi @loop guifg=#e5c07b")
vim.cmd("hi @repeat guifg=#e5c07b")
vim.cmd("hi @operator guifg=#e5c07b")
vim.cmd("hi @punctuation guifg=#e5c07b")
vim.cmd("hi @storageclass guifg=#e5c07b")
